### ISSUE TITLE
`OrtString` missing `Clone` trait

### ISSUE THREAD

**Issue by Zhen-hao** [basile-henry/onnxruntime-rs#14]
hi, thanks for making this project! 
I'm new to Rust. So I might be missing some understanding of the designs here.

Is there a good reason for `OrtString` not to implement the `Clone` trait?

I'm asking because I tried to run the following code.

```Rust
    let output = session.run_raw(
        &ro,
        &in_names.map(|in_name| in_name.as_c_str()).collect::<Box<[_]>>().deref(),
        &[to_tensor::<u32>(attention_mask)?.value(), to_tensor::<u32>(input_ids)?.value(), to_tensor::<u32>(token_type_ids)?.value()],
        &out_names.map(|out_name| out_name.as_c_str()).collect::<Box<[_]>>().deref(),
    )?;
```

but got error
```
126 |         &in_names.map(|in_name| in_name.as_c_str()).collect::<Box<[_]>>().deref(),
    |                                 -------^^^^^^^^^^^
    |                                 |
    |                                 returns a value referencing data owned by the current function
    |                                 `in_name` is borrowed here

error[E0515]: cannot return value referencing function parameter `out_name`
   --> src/main.rs:128:35
    |
128 |         &out_names.map(|out_name| out_name.as_c_str()).collect::<Box<[_]>>().deref(),
    |                                   --------^^^^^^^^^^^
    |                                   |
    |                                   returns a value referencing data owned by the current function
    |                                   `out_name` is borrowed here
```

So, in theory, using `.clone()` before `as_c_str()` would solve this issue.

**Comment by cchalmers** [comment]
Making a `Clone` impl for `OrtString` is _possible_ but it's probably not what you want. Even if you cloned here you'd still have the issue that you're trying to return borrowed data.

You might want to look at the test in `lib.rs` for usage: https://github.com/basile-henry/onnxruntime-rs/blob/master/src/lib.rs#L699-L745. This test also uses the run macro: https://github.com/basile-henry/onnxruntime-rs/blob/master/src/lib.rs#L604-L614 which you might find helpful.

There's also the run example that does this in a more generic way: https://github.com/basile-henry/onnxruntime-rs/blob/master/src/bin/run.rs#L163-L178

Note that this library is still very immature and not really fit for general use yet. A lot of thing are not finished or documented. Issues and PRs are still welcome though!

**Comment by Zhen-hao** [comment]
@cchalmers thanks! I will spend more time reading your code.

Since I'm new to Rust, I might have been talking nonsense.
But I believe building things in Rust is easier than in C++ in the long run.
